"""Piece 2 — SRE postmortem template and markdown rendering.

Section structure follows the Google SRE example postmortem outline
(Summary / Impact / Timeline / Root Cause / Resolution and Recovery /
Detection / Action Items / Lessons Learned) as republished in the
dastergon/postmortem-templates collection (CC0-1.0),
https://github.com/dastergon/postmortem-templates — see the Google SRE
Workbook chapter "Postmortem Culture" for the original outline.

Every section renders with an honesty badge line so a reader can see at a
glance which sections are evidence-linked and which say 'No evidence'.
"""

from __future__ import annotations

from pmg.contracts import Postmortem, SECTION_IDS

# Exact badge lines rendered under each section heading (badge word included
# as plain text so downstream greps work emoji-free too).
BADGE_LINES: dict[str, str] = {
    "green": "🟢 green — every claim linked to evidence",
    "yellow": "🟡 yellow — grounded, some claims unreferenced",
    "red": "🔴 red — no evidence for this section",
}

ROOT_HEADER_NOTE = (
    "Generated by postmortem-generator — every claim links to repository "
    "evidence; sections without evidence say so."
)

SECTION_TITLES: dict[str, str] = {
    "summary": "Summary",
    "impact": "Impact",
    "timeline": "Timeline",
    "root_cause": "Root Cause",
    "detection": "Detection",
    "resolution": "Resolution and Recovery",
    "action_items": "Action Items",
    "lessons": "Lessons Learned",
}

SECTION_GUIDANCE: dict[str, str] = {
    "summary": (
        "Brief executive summary: what was fixed, when, and (if grounded) "
        "which candidate introduced the bug. A few sentences maximum."
    ),
    "impact": (
        "User/customer impact. Repository data alone contains NO impact "
        "information: unless incident telemetry, alerts or reports were "
        "ingested, this section is badge red and must say 'No evidence'. "
        "Never invent affected-user numbers, severity or duration."
    ),
    "timeline": (
        "Dated events reconstructed from repository data only (issues, "
        "commits, releases). Each event line links to its evidence ref."
    ),
    "root_cause": (
        "Technical root cause: what the fix diff shows was wrong, and the "
        "introducer candidate the evidence is consistent with — worded as "
        "candidate evidence, never as proven causality."
    ),
    "detection": (
        "How the bug was found. Git history records no detection story: "
        "unless an advisory or disclosure was ingested, this section is "
        "badge red and must say 'No evidence'."
    ),
    "resolution": (
        "The fix: commit, author, date, files changed and the essential "
        "diff content, all linked to the fix commit."
    ),
    "action_items": (
        "Prevention plan, at most a handful of items, each grounded in "
        "evidence (e.g. regression tests added by the fix, follow-up in the "
        "linked issue). If repository data shows no agreed follow-up, say "
        "'No evidence' instead of padding."
    ),
    "lessons": (
        "What the evidence linkage shows (e.g. introducer-to-fix latency) "
        "plus explicit open questions and honesty caveats."
    ),
}


def _badge_line(badge: str) -> str:
    """Badge line for *badge*; unknown badges render without a claim of meaning."""
    if badge in BADGE_LINES:
        return BADGE_LINES[badge]
    return f"⚪ {badge} — unknown badge (not one of green/yellow/red)"


def _section_markdown(section) -> str:
    lines = [f"## {section.title or SECTION_TITLES.get(section.id, section.id)}"]
    lines.append(_badge_line(section.badge))
    if section.body.strip():
        lines.append(section.body.strip())
    if section.claims:
        claim_lines = []
        for claim in section.claims:
            if claim.refs:
                claim_lines.append(f"- [{', '.join(claim.refs)}] {claim.text}")
            else:
                claim_lines.append(f"- (no evidence ref) {claim.text}")
        lines.append("\n".join(claim_lines))
    return "\n\n".join(lines)


def render_markdown(pm: Postmortem) -> str:
    """Render *pm* as markdown: H1 + generated_by line, then one ``##``
    section per :data:`~pmg.contracts.SECTION_IDS` in canonical order (any
    section with an unknown id is appended at the end in original order)."""
    header = [
        f"# {pm.title}",
        "",
        f"> {ROOT_HEADER_NOTE}",
        ">",
        f"> Generator: {pm.generated_by} · Case: {pm.case}",
        "",
    ]

    canonical = [s for sid in SECTION_IDS for s in pm.sections if s.id == sid]
    extra = [s for s in pm.sections if s.id not in SECTION_IDS]
    body = [_section_markdown(s) for s in canonical + extra]
    return "\n".join(header) + "\n" + "\n\n".join(body) + "\n"
