"""Piece 2 tests — SRE template rendering (offline, no Bob)."""

from __future__ import annotations

from pmg.bob.template import (
    BADGE_LINES,
    SECTION_TITLES,
    render_markdown,
)
from pmg.contracts import (
    BADGES,
    NO_EVIDENCE_PHRASE,
    SECTION_IDS,
    Claim,
    Postmortem,
    Section,
)


def _hand_built_postmortem() -> Postmortem:
    """Postmortem with all 8 sections, one per badge kind, hand-built."""
    badge_cycle = ["green", "yellow", "red"]
    sections: list[Section] = []
    for i, sid in enumerate(SECTION_IDS):
        badge = badge_cycle[i % len(badge_cycle)]
        body = f"Body of {sid}."
        if sid in ("impact", "detection"):
            badge = "red"
            body = (
                f"{NO_EVIDENCE_PHRASE} in repository data — this section "
                "cannot be grounded."
            )
        claims = (
            [Claim(text=f"claim about {sid}", refs=["fix"])]
            if badge != "red"
            else [Claim(text=f"unreferenced claim about {sid}", refs=[])]
        )
        sections.append(
            Section(
                id=sid,
                title=SECTION_TITLES[sid],
                badge=badge,
                body=body,
                claims=claims,
            )
        )
    return Postmortem(
        case="curl-cve-2023-38545",
        title="Postmortem: sample case",
        generated_by="deterministic-fallback",
        sections=sections,
    )


def test_section_titles_cover_all_canonical_ids() -> None:
    assert set(SECTION_TITLES) == set(SECTION_IDS)


def test_render_contains_all_eight_section_titles() -> None:
    md = render_markdown(_hand_built_postmortem())
    for title in SECTION_TITLES.values():
        assert f"## {title}" in md


def test_render_contains_all_badge_lines() -> None:
    md = render_markdown(_hand_built_postmortem())
    for badge, line in BADGE_LINES.items():
        assert badge in BADGES
        assert line in md  # emoji + plain-text badge word
    # each rendered section starts with a badge line right after its heading
    assert md.count("🟢") >= 1 and md.count("🟡") >= 1 and md.count("🔴") >= 2


def test_render_no_evidence_phrase_visible() -> None:
    md = render_markdown(_hand_built_postmortem())
    assert NO_EVIDENCE_PHRASE in md


def test_root_header_note_and_generated_by() -> None:
    pm = _hand_built_postmortem()
    md = render_markdown(pm)
    assert "# Postmortem: sample case" in md
    assert (
        "Generated by postmortem-generator — every claim links to repository "
        "evidence; sections without evidence say so." in md
    )
    assert pm.generated_by in md


def test_claims_render_with_refs_and_unreferenced_marker() -> None:
    md = render_markdown(_hand_built_postmortem())
    assert "- [fix] claim about" in md
    assert "(no evidence ref)" in md


def test_sections_render_in_canonical_order() -> None:
    md = render_markdown(_hand_built_postmortem())
    positions = [md.index(f"## {SECTION_TITLES[sid]}") for sid in SECTION_IDS]
    assert positions == sorted(positions)
